Adding Travis CI
aws-robotics/aws-robomaker-sample-application-voiceinteraction pull request #1
Opened 2018-11-27 06:37 UTC by AAlon

Tested on the fork: https://travis-ci.org/AAlon/aws-robomaker-sample-application-voiceinteraction

2018-11-27 19:52 UTC, timrobotson approved these changes

2018-11-27 22:08 UTC, samuelgundry requested changes

2018-11-27 22:08 UTC, samuelgundry commented on .travis.yml
> +    - ROS_DISTRO="lunar"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu UPSTREAM_WORKSPACE=file $ROSINSTALL_FILENAME="robot_ws/.rosinstall"
Please remove lunar and melodic. RoboMaker does not yet support these and attempting to build is potentially misleading to customers.

2018-11-28 02:28 UTC, AAlon commented on .travis.yml
> +    - ROS_DISTRO="lunar"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu UPSTREAM_WORKSPACE=file $ROSINSTALL_FILENAME="robot_ws/.rosinstall"
Removed unsupported distros, added build jobs without rosinstall.

2018-12-10 21:39 UTC, samuelgundry approved these changes

2018-12-10 21:40 UTC, merged